// Generated by CoffeeScript 2.3.1
(function() {
  var app, booksRouter, cookieParser, createError, express, indexRouter, initCouch, logger, path;

  createError = require('http-errors');

  express = require('express');

  path = require('path');

  cookieParser = require('cookie-parser');

  logger = require('morgan');

  initCouch = require('./init_couch');

  initCouch(function(err) {
    if (err) {
      throw err;
    } else {
      console.log('couchdb initialized');
    }
  });

  //require routes
  indexRouter = require('./routes/index');

  booksRouter = require('./routes/books');

  app = express();

  // view engine setup
  app.set('views', path.join(__dirname, 'views'));

  app.set('view engine', 'pug');

  app.use(logger('dev'));

  app.use(express.json());

  app.use(express.urlencoded({
    extended: false
  }));

  app.use(cookieParser());

  app.use(express.static(path.join(__dirname, 'public')));

  //purecss files
  app.use('/pure', express.static(__dirname + '/node_modules/purecss/build'));

  app.use('/', indexRouter);

  app.use('/books', booksRouter);

  //catch 404 and forward to error handler
  app.use(function(req, res, next) {
    next(createError(404));
  });

  // error handler
  app.use(function(err, req, res, next) {
    res.locals.message = err.message;
    res.locals.error = req.app.get('env') === 'development' ? err : {};
    // render the error page
    res.status(err.status || 500);
    res.render('error');
  });

  module.exports = app;

}).call(this);
