// Generated by CoffeeScript 2.3.1
(function() {
  var async, couch, createDatabase, createDatabases, databases, initCouch;

  async = require('async');

  couch = require('./couchdb');

  databases = ['books'];

  initCouch = function(cb) {
    return createDatabases(cb);
  };

  createDatabases = function(cb) {
    return async.each(databases, createDatabase, cb);
  };

  createDatabase = function(db, cb) {
    return couch.db.create(db, function(err) {
      if (err && err.statusCode === 412) {
        err = null;
      }
      return cb(err);
    });
  };

  module.exports = initCouch;

}).call(this);
