// Generated by CoffeeScript 2.3.1
(function() {
  var booksModel, express, hash, router, timestamp;

  express = require('express');

  router = express.Router();

  hash = require('object-hash');

  booksModel = require('../models/booksModel');

  timestamp = require('time-stamp');

  // GET home page.
  router.get('/', function(req, res) {
    var booksList, msg, show;
    booksList = booksModel.getAll(true);
    if (!booksList) {
      show = true;
      msg = 'Error on get books';
    } else {
      show = false;
      msg = 'page open';
    }
    res.render('books', {
      title: 'Books',
      data: booksList,
      message: {
        show: show,
        msg: msg
      }
    });
  });

  router.get('/createPage', function(req, res) {
    res.render('booksCreate', {
      title: 'Create a Book',
      message: {
        show: false,
        msg: 'page open'
      },
      data: {
        book_id: req.book_id || '',
        book_name: req.book_name || ''
      }
    });
  });

  router.post('/create', function(req, res) {
    var myHash, obj;
    req.body.book_timestamp = timestamp('YYYYMMDDmmss');
    myHash = hash(req.body);
    obj = booksModel.create(req.body, myHash);
    if (obj) {
      req.showMsg = true;
      req.msgMsg = 'Book has been created';
      res.redirect('/books');
    } else {
      // res.render 'books',
      // title: 'books',
      // message:
      //   show: true
      //   msg: 'Book has been created'
      res.render('booksCreate', {
        title: 'Create a book',
        message: {
          show: true,
          msg: 'An error on create book has ocurred'
        },
        data: {
          book_id: '',
          book_name: req.body.book_name
        }
      });
    }
  });

  module.exports = router;

}).call(this);
