// Generated by CoffeeScript 2.3.1
(function() {
  var express, router;

  express = require('express');

  router = express.Router();

  // GET home page.
  router.get('/', function(req, res, next) {
    res.render('index', {
      title: 'express-test'
    });
  });

  module.exports = router;

}).call(this);
