// Generated by CoffeeScript 2.3.1
(function() {
  var books;

  books = require('../couchdb').use('books');

  exports.create = function(book, myHash) {
    return books.insert({
      _id: myHash,
      timestamp: book.book_timestamp,
      name: book.book_name
    }, function(err, body) {
      if (err) {
        return false;
      } else {
        return true;
      }
    });
  };

  exports.delete = function(book) {
    return books.get(book.book_id, function(err, body) {
      books.destroy(body._id, body._rev, function(err, body) {
        if (err) {
          return false;
        } else {
          return true;
        }
      });
    });
  };

  exports.getAll = function(docs) {
    return books.list({
      include_docs: docs
    }, function(err, body) {
      var content;
      if (err) {
        return false;
      } else {
        content = [];
        body.rows.forEach(function(doc) {
          return content.push(doc.doc);
        });
        return content;
      }
    });
  };

}).call(this);
